### ISSUE TITLE
C1 C6 C10 大小

### ISSUE THREAD

**Issue by CraneJen** [foggyhlw/Motion-Sensor#1]
C1 C6 C10 BOM表与原理图标注不一样啊

**Comment by yj82871002** [comment]
> 



> C1 C6 C10 BOM表与原理图标注不一样啊

同问 有答案么，根据原理图焊还是bom表

**Comment by foggyhlw** [comment]
> C1 C6 C10 BOM表与原理图标注不一样啊

都是0.1uf，可能bom导出时候有点问题，立创eda里面的值和名称没弄好。
